---

- name: import tasks install
  import_tasks: install.yml
  when: not (pwgen_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - pwgen

- name: import tasks remove
  import_tasks: remove.yml
  when: (pwgen_state is match('false|no|remove'))
  tags:
    - pwgen
