---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - dsniff

- name: install package dsniff
  package:
    state: 'present'
    name: "{{package_name_dsniff}}"
  tags:
    - dsniff
