---

- name: import tasks install
  import_tasks: install.yml
  when: not (dsniff_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - dsniff

- name: import tasks remove
  import_tasks: remove.yml
  when: (dsniff_state is match('false|no|remove'))
  tags:
    - dsniff
