---

- name: import tasks install
  import_tasks: install.yml
  when: not (unzip_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - unzip

- name: import tasks remove
  import_tasks: remove.yml
  when: (unzip_state is match('false|no|remove'))
  tags:
    - unzip
