---

- name: import tasks install
  import_tasks: install.yml
  when: not (stress_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - stress

- name: import tasks remove
  import_tasks: remove.yml
  when: (stress_state is match('false|no|remove'))
  tags:
    - stress
