---

- name: import tasks install
  import_tasks: install.yml
  when: not (hping2_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - hping2

- name: import tasks remove
  import_tasks: remove.yml
  when: (hping2_state is match('false|no|remove'))
  tags:
    - hping2
