---

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - openbsd_pf

- name: 'file create anchors.conf'
  template:
    src: "{{file_src_anchors_conf}}"
    dest: "{{file_dst_anchors_conf}}"
    mode: "{{file_mode_anchors_conf}}"
    owner: "{{file_owner_anchors_conf}}"
    group: "{{file_group_anchors_conf}}"
  notify:
    - 'command validate openbsd_pf'
    - 'command reload openbsd_pf'
  tags:
    - openbsd_pf

- name: 'file create filters.conf'
  template:
    src: "{{file_src_filters_conf}}"
    dest: "{{file_dst_filters_conf}}"
    mode: "{{file_mode_filters_conf}}"
    owner: "{{file_owner_filters_conf}}"
    group: "{{file_group_filters_conf}}"
  notify:
    - 'command validate openbsd_pf'
    - 'command reload openbsd_pf'
  tags:
    - openbsd_pf

- name: 'file create macros.conf'
  template:
    src: "{{file_src_macros_conf}}"
    dest: "{{file_dst_macros_conf}}"
    mode: "{{file_mode_macros_conf}}"
    owner: "{{file_owner_macros_conf}}"
    group: "{{file_group_macros_conf}}"
  notify:
    - 'command validate openbsd_pf'
    - 'command reload openbsd_pf'
  tags:
    - openbsd_pf

- name: 'file create normalization.conf'
  template:
    src: "{{file_src_normalization_conf}}"
    dest: "{{file_dst_normalization_conf}}"
    mode: "{{file_mode_normalization_conf}}"
    owner: "{{file_owner_normalization_conf}}"
    group: "{{file_group_normalization_conf}}"
  notify:
    - 'command validate openbsd_pf'
    - 'command reload openbsd_pf'
  tags:
    - openbsd_pf

- name: 'file create options.conf'
  template:
    src: "{{file_src_options_conf}}"
    dest: "{{file_dst_options_conf}}"
    mode: "{{file_mode_options_conf}}"
    owner: "{{file_owner_options_conf}}"
    group: "{{file_group_options_conf}}"
  notify:
    - 'command validate openbsd_pf'
    - 'command reload openbsd_pf'
  tags:
    - openbsd_pf

- name: 'file create queues.conf'
  template:
    src: "{{file_src_queues_conf}}"
    dest: "{{file_dst_queues_conf}}"
    mode: "{{file_mode_queues_conf}}"
    owner: "{{file_owner_queues_conf}}"
    group: "{{file_group_queues_conf}}"
  notify:
    - 'command validate openbsd_pf'
    - 'command reload openbsd_pf'
  tags:
    - openbsd_pf

- name: 'file create tables.conf'
  template:
    src: "{{file_src_tables_conf}}"
    dest: "{{file_dst_tables_conf}}"
    mode: "{{file_mode_tables_conf}}"
    owner: "{{file_owner_tables_conf}}"
    group: "{{file_group_tables_conf}}"
  notify:
    - 'command validate openbsd_pf'
    - 'command reload openbsd_pf'
  tags:
    - openbsd_pf

- name: 'file create pf.conf'
  template:
    src: "{{file_src_pf_conf}}"
    dest: "{{file_dst_pf_conf}}"
    mode: "{{file_mode_pf_conf}}"
    owner: "{{file_owner_pf_conf}}"
    group: "{{file_group_pf_conf}}"
  notify:
    - 'command validate openbsd_pf'
    - 'command reload openbsd_pf'
  tags:
    - openbsd_pf

- name: 'command status openbsd_pf'
  command: "{{command_cmd_status_openbsd_pf}}"
  register: register_status_openbsd_pf
  changed_when: (register_status_openbsd_pf.rc > 1)
  failed_when: (register_status_openbsd_pf.rc > 1)
  check_mode: 'no'
  tags:
    - openbsd_pf

- name: 'command enable openbsd_pf'
  command: "{{command_cmd_enable_openbsd_pf}}"
  when: (register_status_openbsd_pf.rc == 1)
  check_mode: 'no'
  tags:
    - openbsd_pf

- name: 'command check openbsd_pf'
  shell: "{{command_cmd_check_openbsd_pf}}"
  register: register_check_openbsd_pf
  changed_when: (register_check_openbsd_pf.rc > 1)
  failed_when: (register_check_openbsd_pf.rc > 1)
  check_mode: 'no'
  tags:
    - openbsd_pf

- name: 'command start openbsd_pf'
  command: "{{command_cmd_start_openbsd_pf}}"
  when: (register_check_openbsd_pf.rc == 1)
  check_mode: 'no'
  tags:
    - openbsd_pf
