---

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - openbsd_pf

- name: 'command status openbsd_pf'
  command: "{{command_cmd_status_openbsd_pf}}"
  register: register_status_openbsd_pf
  changed_when: (register_status_openbsd_pf.rc > 1)
  failed_when: (register_status_openbsd_pf.rc > 1)
  check_mode: 'no'
  tags:
    - openbsd_pf

- name: 'command disable openbsd_pf'
  command: "{{command_cmd_disable_openbsd_pf}}"
  when: (register_status_openbsd_pf.rc == 0)
  check_mode: 'no'
  tags:
    - openbsd_pf

- name: 'command check openbsd_pf'
  shell: "{{command_cmd_check_openbsd_pf}}"
  register: register_check_openbsd_pf
  changed_when: (register_check_openbsd_pf.rc > 1)
  failed_when: (register_check_openbsd_pf.rc > 1)
  check_mode: 'no'
  tags:
    - openbsd_pf

- name: 'command stop openbsd_pf'
  command: "{{command_cmd_stop_openbsd_pf}}"
  when: (register_check_openbsd_pf.rc == 0)
  check_mode: 'no'
  tags:
    - openbsd_pf

- name: 'file remove anchors.conf'
  file:
    state: 'absent'
    path: "{{file_dst_anchors_conf}}"
  tags:
    - openbsd_pf

- name: 'file remove filters.conf'
  file:
    state: 'absent'
    path: "{{file_dst_filters_conf}}"
  tags:
    - openbsd_pf

- name: 'file remove macros.conf'
  file:
    state: 'absent'
    path: "{{file_dst_macros_conf}}"
  tags:
    - openbsd_pf

- name: 'file remove normalization.conf'
  file:
    state: 'absent'
    path: "{{file_dst_normalization_conf}}"
  tags:
    - openbsd_pf

- name: 'file remove options.conf'
  file:
    state: 'absent'
    path: "{{file_dst_options_conf}}"
  tags:
    - openbsd_pf

- name: 'file remove queues.conf'
  file:
    state: 'absent'
    path: "{{file_dst_queues_conf}}"
  tags:
    - openbsd_pf

- name: 'file remove tables.conf'
  file:
    state: 'absent'
    path: "{{file_dst_tables_conf}}"
  tags:
    - openbsd_pf

- name: 'file remove pf.conf'
  file:
    state: 'absent'
    path: "{{file_dst_pf_conf}}"
  tags:
    - openbsd_pf

- name: 'file remove pf.dir'
  file:
    state: 'absent'
    path: "{{file_dst_ntp_script_dir}}"
  tags:
    - openbsd_pf
