---

- name: import tasks install
  import_tasks: install.yml
  when: not (iperf3_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - iperf3

- name: import tasks remove
  import_tasks: remove.yml
  when: (iperf3_state is match('false|no|remove'))
  tags:
    - iperf3
