---

- name: import tasks install
  import_tasks: install.yml
  when: not (patchutils_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - patchutils

- name: import tasks remove
  import_tasks: remove.yml
  when: (patchutils_state is match('false|no|remove'))
  tags:
    - patchutils
