---

- name: 'task include install'
  import_tasks: install.yml
  when: not (ca_root_nss_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - ca_root_nss

- name: 'task include remove'
  import_tasks: remove.yml
  when: (ca_root_nss_state is match('false|no|remove'))
  tags:
    - ca_root_nss
