---

- name: import tasks install
  import_tasks: install.yml
  when: not (ssldump_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - ssldump

- name: import tasks remove
  import_tasks: remove.yml
  when: (ssldump_state is match('false|no|remove'))
  tags:
    - ssldump
