---

- name: import tasks install
  import_tasks: install.yml
  when: not (usbutils_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - usbutils

- name: import tasks remove
  import_tasks: remove.yml
  when: (usbutils_state is match('false|no|remove'))
  tags:
    - usbutils
