---

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - nginx

- name: 'file create nginx.conf'
  template:
    src: "{{file_src_nginx_conf}}"
    dest: "{{file_dst_nginx_conf}}"
    mode: "{{file_mode_nginx_conf}}"
    owner: "{{file_owner_nginx_conf}}"
    group: "{{file_group_nginx_conf}}"
  notify: 'command check nginx'
  tags:
    - nginx

- name: 'line disable nginx_enable'
  lineinfile:
    state: 'present'
    line: "{{file_line_nginx_enable}}=\"NO\" # Ansible: Disable nginx"
    regexp: "^{{file_line_nginx_enable}}="
    dest: "{{file_dst_nginx_enable}}"
    create: 'yes'
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - nginx

- name: 'file create nginx.cfg'
  template:
    src: "{{file_src_nginx_cfg}}"
    dest: "{{file_dst_nginx_cfg}}"
    mode: "{{file_mode_nginx_cfg}}"
    owner: "{{file_owner_nginx_cfg}}"
    group: "{{file_group_nginx_cfg}}"
  notify: 'service reload monit'
  when: (nginx_monitor_monit_state is match('true|yes|enable'))
  tags:
    - nginx

- name: 'command status nginx'
  command: "{{command_cmd_status_nginx}}"
  register: register_status_nginx
  changed_when: (register_status_nginx.rc > 1)
  failed_when: (register_status_nginx.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - nginx

- name: 'command disable nginx'
  command: "{{command_cmd_disable_nginx}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_status_nginx.rc == 0)
  tags:
    - nginx

- name: 'command check nginx'
  command: "{{command_cmd_check_nginx}}"
  register: register_check_nginx
  changed_when: (register_check_nginx.rc > 1)
  failed_when: (register_check_nginx.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - nginx

- name: 'command stop nginx'
  command: "{{command_cmd_stop_nginx}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_check_nginx.rc == 0)
  tags:
    - nginx

- name: 'service stop nginx'
  service:
    state: 'stopped'
    enabled: 'no'
    name: "{{service_name_nginx}}"
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - nginx
