---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - tinc

- name: create file tinc.cfg
  template:
    src: "{{file_src_tinc_cfg}}"
    dest: "{{file_dst_tinc_cfg}}"
    mode: "{{file_mode_tinc_cfg}}"
    owner: "{{file_owner_tinc_cfg}}"
    group: "{{file_group_tinc_cfg}}"
  notify: reload service monit
  when: (tinc_monitor_monit_state is match('true|yes|enable'))
  tags:
    - tinc

- name: status tinc
  command: "{{command_cmd_status_tinc}}"
  register: register_status_tinc
  changed_when: (register_status_tinc.rc > 1)
  failed_when: (register_status_tinc.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - tinc

- name: enable tinc
  command: "{{command_cmd_enable_tinc}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_status_tinc.rc == 1)
  tags:
    - tinc

- name: check tinc
  command: "{{command_cmd_check_tinc}}"
  register: register_check_tinc
  changed_when: (register_check_tinc.rc > 1)
  failed_when: (register_check_tinc.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - tinc

- name: start tinc
  command: "{{command_cmd_start_tinc}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_check_tinc.rc == 1)
  tags:
    - tinc
