---

- name: import tasks install
  import_tasks: install.yml
  when: not (picocom_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - picocom

- name: import tasks remove
  import_tasks: remove.yml
  when: (picocom_state is match('false|no|remove'))
  tags:
    - picocom
