---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - openntpd

- name: create file ntpd.conf
  template:
    src: "{{file_src_ntpd_conf}}"
    dest: "{{file_dst_ntpd_conf}}"
    mode: "{{file_mode_ntpd_conf}}"
    owner: "{{file_owner_ntpd_conf}}"
    group: "{{file_group_ntpd_conf}}"
  tags:
    - openntpd

- name: remove file openntpd_check-time
  file:
    state: 'absent'
    path: "{{file_dst_openntpd_check_time}}"
  tags:
    - openntpd

- name: create cron openntpd_check-time
  cron:
    state: 'present'
    disabled: 'yes'
    name: "{{cron_name_openntpd_check_time}}"
    day: "{{cron_day_openntpd_check_time}}"
    hour: "{{cron_hour_openntpd_check_time}}"
    minute: "{{cron_minute_openntpd_check_time}}"
    month: "{{cron_month_openntpd_check_time}}"
    weekday: "{{cron_weekday_openntpd_check_time}}"
    user: "{{cron_user_openntpd_check_time}}"
    job: "{{cron_job_openntpd_check_time}}"
  tags:
    - openntpd

- name: line disable openntpd_enable
  lineinfile:
    state: 'present'
    line: "{{file_line_openntpd_enable}}=\"NO\" # Ansible: Disable openntpd"
    regexp: "^{{file_line_openntpd_enable}}="
    dest: "{{file_dst_openntpd_enable}}"
    create: 'yes'
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - openntpd

- name: create file openntpd.cfg
  template:
    src: "{{file_src_openntpd_cfg}}"
    dest: "{{file_dst_openntpd_cfg}}"
    mode: "{{file_mode_openntpd_cfg}}"
    owner: "{{file_owner_openntpd_cfg}}"
    group: "{{file_group_openntpd_cfg}}"
  notify: reload service monit
  when: (openntpd_monitor_monit_state is match('true|yes|enable'))
  tags:
    - openntpd

- name: status openntpd
  command: "{{command_cmd_status_openntpd}}"
  register: register_status_openntpd
  changed_when: (register_status_openntpd.rc > 1)
  failed_when: (register_status_openntpd.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - openntpd

- name: disable openntpd
  command: "{{command_cmd_disable_openntpd}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_status_openntpd.rc == 0)
  tags:
    - openntpd

- name: check openntpd
  command: "{{command_cmd_check_openntpd}}"
  register: register_check_openntpd
  changed_when: (register_check_openntpd.rc > 1)
  failed_when: (register_check_openntpd.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - openntpd

- name: stop openntpd
  command: "{{command_cmd_stop_openntpd}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_check_openntpd.rc == 0)
  tags:
    - openntpd

- name: stop service openntpd
  service:
    state: 'stopped'
    enabled: 'no'
    name: "{{service_name_openntpd}}"
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - openntpd
