---

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - openntpd

- name: 'file create ntpd.conf'
  template:
    src: "{{file_src_ntpd_conf}}"
    dest: "{{file_dst_ntpd_conf}}"
    mode: "{{file_mode_ntpd_conf}}"
    owner: "{{file_owner_ntpd_conf}}"
    group: "{{file_group_ntpd_conf}}"
  notify: 'service restart openntpd'
  tags:
    - openntpd

- name: 'file create openntpd_check-time'
  template:
    src: "{{file_src_openntpd_check_time}}"
    dest: "{{file_dst_openntpd_check_time}}"
    mode: "{{file_mode_openntpd_check_time}}"
    owner: "{{file_owner_openntpd_check_time}}"
    group: "{{file_group_openntpd_check_time}}"
  tags:
    - openntpd

- name: 'cron create openntpd_check-time'
  cron:
    state: 'present'
    disabled: "{{'yes' if (openntpd_check_time_state is match('false|no|disable')) else 'no'}}"
    name: "{{cron_name_openntpd_check_time}}"
    day: "{{cron_day_openntpd_check_time}}"
    hour: "{{cron_hour_openntpd_check_time}}"
    minute: "{{cron_minute_openntpd_check_time}}"
    month: "{{cron_month_openntpd_check_time}}"
    weekday: "{{cron_weekday_openntpd_check_time}}"
    user: "{{cron_user_openntpd_check_time}}"
    job: "{{cron_job_openntpd_check_time}}"
  tags:
    - openntpd

- name: 'line enable openntpd_enable'
  lineinfile:
    state: 'present'
    line: "{{file_line_openntpd_enable}}=\"YES\" # Ansible: Enable openntpd"
    regexp: "^{{file_line_openntpd_enable}}="
    dest: "{{file_dst_openntpd_enable}}"
    create: 'yes'
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - openntpd

- name: 'file create openntpd.cfg'
  template:
    src: "{{file_src_openntpd_cfg}}"
    dest: "{{file_dst_openntpd_cfg}}"
    mode: "{{file_mode_openntpd_cfg}}"
    owner: "{{file_owner_openntpd_cfg}}"
    group: "{{file_group_openntpd_cfg}}"
  notify: 'service reload monit'
  when: (openntpd_monitor_monit_state is match('true|yes|enable'))
  tags:
    - openntpd

- name: 'command status openntpd'
  command: "{{command_cmd_status_openntpd}}"
  register: register_status_openntpd
  changed_when: (register_status_openntpd.rc > 1)
  failed_when: (register_status_openntpd.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - openntpd

- name: 'command enable openntpd'
  command: "{{command_cmd_enable_openntpd}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_status_openntpd.rc == 1)
  tags:
    - openntpd

- name: 'command check openntpd'
  command: "{{command_cmd_check_openntpd}}"
  register: register_check_openntpd
  changed_when: (register_check_openntpd.rc > 1)
  failed_when: (register_check_openntpd.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - openntpd

- name: 'command start openntpd'
  command: "{{command_cmd_start_openntpd}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_check_openntpd.rc == 1)
  tags:
    - openntpd

- name: 'service start openntpd'
  service:
    state: 'started'
    enabled: 'yes'
    name: "{{service_name_openntpd}}"
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - openntpd
