---

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - openntpd

- name: 'command status openntpd'
  command: "{{command_cmd_status_openntpd}}"
  register: register_status_openntpd
  changed_when: (register_status_openntpd.rc > 1)
  failed_when: (register_status_openntpd.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - openntpd

- name: 'command disable openntpd'
  command: "{{command_cmd_disable_openntpd}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_status_openntpd.rc == 0)
  tags:
    - openntpd

- name: 'command check openntpd'
  command: "{{command_cmd_check_openntpd}}"
  register: register_check_openntpd
  changed_when: (register_check_openntpd.rc > 1)
  failed_when: (register_check_openntpd.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - openntpd

- name: 'command stop openntpd'
  command: "{{command_cmd_stop_openntpd}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_check_openntpd.rc == 0)
  tags:
    - openntpd

- name: 'package remove openntpd'
  package:
    state: 'absent'
    name: "{{package_name_openntpd}}"
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - openntpd

- name: 'file remove openntpd.cfg'
  file:
    state: 'absent'
    path: "{{file_dst_openntpd_cfg}}"
  notify: 'service reload monit'
  tags:
    - openntpd

- name: 'cron remove openntpd_check-time'
  cron:
    state: 'absent'
    name: "{{cron_name_openntpd_check_time}}"
    user: "{{cron_user_openntpd_check_time}}"
  tags:
    - openntpd

- name: 'file remove openntpd_check-time'
  file:
    state: 'absent'
    path: "{{file_dst_openntpd_check_time}}"
  tags:
    - openntpd

- name: 'line remove openntpd_enable'
  lineinfile:
    state: 'absent'
    line: "{{file_line_openntpd_enable}}=\"NO\" # Ansible: Remove openntpd"
    regexp: "^{{file_line_openntpd_enable}}="
    dest: "{{file_dst_openntpd_enable}}"
    create: 'yes'
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - openntpd

- name: 'file remove ntpd.conf'
  file:
    state: 'absent'
    path: "{{file_dst_ntpd_conf}}"
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - openntpd
