---

- name: import tasks install
  import_tasks: install.yml
  when: not (ltrace_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - ltrace

- name: import tasks remove
  import_tasks: remove.yml
  when: (ltrace_state is match('false|no|remove'))
  tags:
    - ltrace
