---

- name: import tasks install
  import_tasks: install.yml
  when: not (scrub_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - scrub

- name: import tasks remove
  import_tasks: remove.yml
  when: (scrub_state is match('false|no|remove'))
  tags:
    - scrub
