---

- name: import tasks install
  import_tasks: install.yml
  when: not (siege_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - siege

- name: import tasks remove
  import_tasks: remove.yml
  when: (siege_state is match('false|no|remove'))
  tags:
    - siege
