---

- name: import tasks install
  import_tasks: install.yml
  when: not (socat_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - socat

- name: import tasks remove
  import_tasks: remove.yml
  when: (socat_state is match('false|no|remove'))
  tags:
    - socat
