---

- name: import tasks install
  import_tasks: install.yml
  when: not (curl_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - curl

- name: import tasks remove
  import_tasks: remove.yml
  when: (curl_state is match('false|no|remove'))
  tags:
    - curl
