---

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'

- name: 'command validate openssh'
  command: "{{command_cmd_validate_openssh}}"

- name: 'service reload monit'
  service:
    state: 'reloaded'
    name: "{{service_name_monit}}"
  when: (register_check_service_monit.rc == 0)

- name: 'service reload openssh'
  service:
    state: 'reloaded'
    name: "{{service_name_openssh}}"
