---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - opensmtpd

- name: create file aliases
  template:
    src: "{{file_src_aliases}}"
    dest: "{{file_dst_aliases}}"
    mode: "{{file_mode_aliases}}"
    owner: "{{file_owner_aliases}}"
    group: "{{file_group_aliases}}"
  notify:
    - start service opensmtpd
    - smtpctl aliases
    - restart service opensmtpd
  tags:
    - opensmtpd

- name: create file secrets
  template:
    src: "{{file_src_secrets}}"
    dest: "{{file_dst_secrets}}"
    mode: "{{file_mode_secrets}}"
    owner: "{{file_owner_secrets}}"
    group: "{{file_group_secrets}}"
  no_log: 'true'
  notify: restart service opensmtpd
  tags:
    - opensmtpd

- name: create file smtpd.conf
  template:
    src: "{{file_src_smtpd_conf}}"
    dest: "{{file_dst_smtpd_conf}}"
    mode: "{{file_mode_smtpd_conf}}"
    owner: "{{file_owner_smtpd_conf}}"
    group: "{{file_group_smtpd_conf}}"
  notify: restart service opensmtpd
  tags:
    - opensmtpd

- name: create file opensmtpd.cfg
  template:
    src: "{{file_src_opensmtpd_cfg}}"
    dest: "{{file_dst_opensmtpd_cfg}}"
    mode: "{{file_mode_opensmtpd_cfg}}"
    owner: "{{file_owner_opensmtpd_cfg}}"
    group: "{{file_group_opensmtpd_cfg}}"
  notify: reload service monit
  when: (opensmtpd_monitor_monit_state is match('true|yes|enable'))
  tags:
    - opensmtpd

- name: status opensmtpd
  command: "{{command_cmd_status_opensmtpd}}"
  register: register_status_opensmtpd
  changed_when: (register_status_opensmtpd.rc > 1)
  failed_when: (register_status_opensmtpd.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - opensmtpd

- name: enable opensmtpd
  command: "{{command_cmd_enable_opensmtpd}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_status_opensmtpd.rc == 1)
  tags:
    - opensmtpd

- name: check opensmtpd
  command: "{{command_cmd_check_opensmtpd}}"
  register: register_check_opensmtpd
  changed_when: (register_check_opensmtpd.rc > 1)
  failed_when: (register_check_opensmtpd.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - opensmtpd

- name: start opensmtpd
  command: "{{command_cmd_start_opensmtpd}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_check_opensmtpd.rc == 1)
  tags:
    - opensmtpd
