---

- name: 'task include install'
  import_tasks: install.yml
  when: not (apachetop_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - apachetop

- name: 'task include remove'
  import_tasks: remove.yml
  when: (apachetop_state is match('false|no|remove'))
  tags:
    - apachetop
