---

- name: import tasks install
  import_tasks: install.yml
  when: not (apachetop_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - apachetop

- name: import tasks remove
  import_tasks: remove.yml
  when: (apachetop_state is match('false|no|remove'))
  tags:
    - apachetop
