---

- name: import tasks install
  import_tasks: install.yml
  when: not (zfs_stats_lite_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - zfs_stats_lite

- name: import tasks remove
  import_tasks: remove.yml
  when: (zfs_stats_lite_state is match('false|no|remove'))
  tags:
    - zfs_stats_lite
