---

- name: import tasks install
  import_tasks: install.yml
  when: not (hostname_if_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - hostname_if

- name: import tasks config
  import_tasks: config.yml
  when: not (hostname_if_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - hostname_if
