---

- name: import tasks install
  import_tasks: install.yml
  when: not (openssl_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - openssl

- name: import tasks remove
  import_tasks: remove.yml
  when: (openssl_state is match('false|no|remove'))
  tags:
    - openssl
