---

- name: import tasks install
  import_tasks: install.yml
  when: not (drill_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - drill

- name: import tasks remove
  import_tasks: remove.yml
  when: (drill_state is match('false|no|remove'))
  tags:
    - drill
