---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - main_pkg

- name: create file FreeBSD.conf
  template:
    src: "{{file_src_freebsd_conf}}"
    dest: "{{file_dst_freebsd_conf}}"
    mode: "{{file_mode_freebsd_conf}}"
    owner: "{{file_owner_freebsd_conf}}"
    group: "{{file_group_freebsd_conf}}"
  tags:
    - main_pkg

- name: create file pkg.conf
  template:
    src: "{{file_src_pkg_conf}}"
    dest: "{{file_dst_pkg_conf}}"
    mode: "{{file_mode_pkg_conf}}"
    owner: "{{file_owner_pkg_conf}}"
    group: "{{file_group_pkg_conf}}"
  tags:
    - main_pkg
