---

- name: import tasks install
  import_tasks: install.yml
  when: not (mtr_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - mtr

- name: import tasks remove
  import_tasks: remove.yml
  when: (mtr_state is match('false|no|remove'))
  tags:
    - mtr
