---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - suricata

- name: config line suricata_flags
  lineinfile:
    state: 'present'
    line: "{{file_line_suricata_flags}}-i {{suricata_interface}} # Ansible: Configure suricata"
    regexp: "^{{file_line_suricata_flags}}"
    dest: "{{file_dst_suricata_flags}}"
    create: 'yes'
  notify: reload service suricata
  tags:
    - suricata

- name: create file suricata.yaml
  template:
    src: "{{file_src_suricata_yaml}}"
    dest: "{{file_dst_suricata_yaml}}"
    mode: "{{file_mode_suricata_yaml}}"
    owner: "{{file_owner_suricata_yaml}}"
    group: "{{file_group_suricata_yaml}}"
    validate: "{{file_validate_suricata_yaml}}"
  notify: reload service suricata
  tags:
    - suricata

- name: create file suricata.cfg
  template:
    src: "{{file_src_suricata_cfg}}"
    dest: "{{file_dst_suricata_cfg}}"
    mode: "{{file_mode_suricata_cfg}}"
    owner: "{{file_owner_suricata_cfg}}"
    group: "{{file_group_suricata_cfg}}"
  notify: reload service monit
  when: (suricata_monitor_monit_state is match('true|yes|enable'))
  tags:
    - suricata

- name: status suricata
  command: "{{command_cmd_status_suricata}}"
  register: register_status_suricata
  changed_when: (register_status_suricata.rc > 1)
  failed_when: (register_status_suricata.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - suricata

- name: enable suricata
  command: "{{command_cmd_enable_suricata}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_status_suricata.rc == 1)
  tags:
    - suricata

- name: check suricata
  command: "{{command_cmd_check_suricata}}"
  register: register_check_suricata
  changed_when: (register_check_suricata.rc > 1)
  failed_when: (register_check_suricata.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - suricata

- name: start suricata
  command: "{{command_cmd_start_suricata}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_check_suricata.rc == 1)
  tags:
    - suricata

- name: start service suricata
  service:
    state: 'started'
    enabled: 'yes'
    name: "{{service_name_suricata}}"
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - suricata
