---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - suricata

- name: line remove eve.json.newsyslog
  lineinfile:
    state: 'absent'
    regexp: "{{file_regexp_eve_json_newsyslog}}"
    dest: "{{file_dst_eve_json_newsyslog}}"
    create: 'yes'
  tags:
    - suricata

- name: line remove fast.log.newsyslog
  lineinfile:
    state: 'absent'
    regexp: "{{file_regexp_fast_log_newsyslog}}"
    dest: "{{file_dst_fast_log_newsyslog}}"
    create: 'yes'
  tags:
    - suricata

- name: line remove stats.log.newsyslog
  lineinfile:
    state: 'absent'
    regexp: "{{file_regexp_stats_log_newsyslog}}"
    dest: "{{file_dst_stats_log_newsyslog}}"
    create: 'yes'
  tags:
    - suricata

- name: line remove suricata_flags
  lineinfile:
    state: 'absent'
    regexp: "^{{file_line_suricata_flags}}.*"
    dest: "{{file_dst_suricata_flags}}"
    create: 'yes'
  tags:
    - suricata

- name: info suricata
  shell: "{{command_cmd_info_suricata}}"
  register: register_info_suricata
  failed_when: (register_info_suricata.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - suricata

- name: disable suricata
  command: "{{command_cmd_disable_suricata}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_info_suricata.rc == 0)
  tags:
    - suricata

- name: stop suricata
  command: "{{command_cmd_stop_suricata}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_info_suricata.rc == 0)
  tags:
    - suricata

- name: remove package suricata
  package:
    state: 'absent'
    name: "{{package_name_suricata}}"
  tags:
    - suricata

- name: remove file suricata.cfg
  file:
    state: 'absent'
    path: "{{file_dst_suricata_cfg}}"
  notify: reload service monit
  tags:
    - suricata

- name: remove file suricata.yaml
  file:
    state: 'absent'
    path: "{{file_dst_suricata_yaml}}"
  tags:
    - suricata

- name: remove file suricata.rules
  file:
    state: 'absent'
    path: "{{file_dst_suricata_rules}}"
  tags:
    - suricata
