---

- name: import tasks install
  import_tasks: install.yml
  when: not (motd_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - motd

- name: import tasks remove
  import_tasks: remove.yml
  when: (motd_state is match('false|no|remove'))
  tags:
    - motd
