---

- name: import tasks install
  import_tasks: install.yml
  when: not (sdparm_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - sdparm

- name: import tasks remove
  import_tasks: remove.yml
  when: (sdparm_state is match('false|no|remove'))
  tags:
    - sdparm
