---

- name: import tasks install
  import_tasks: install.yml
  when: not (tcpreplay_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - tcpreplay

- name: import tasks remove
  import_tasks: remove.yml
  when: (tcpreplay_state is match('false|no|remove'))
  tags:
    - tcpreplay
