---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - remove
    - unbound

#-------------------------------------------------------------------------------
# COMMANDS
#-------------------------------------------------------------------------------

- name: 'command status unbound'
  command: "{{command_cmd_status_unbound}}"
  register: register_status_unbound
  changed_when: (register_status_unbound.rc > 1)
  failed_when: (register_status_unbound.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - remove
    - unbound

- name: 'command disable unbound'
  command: "{{command_cmd_disable_unbound}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_status_unbound.rc == 0)
  tags:
    - remove
    - unbound

- name: 'command check unbound'
  command: "{{command_cmd_check_unbound}}"
  register: register_check_unbound
  changed_when: (register_check_unbound.rc > 1)
  failed_when: (register_check_unbound.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - remove
    - unbound

- name: 'command stop unbound'
  command: "{{command_cmd_stop_unbound}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_check_unbound.rc == 0)
  tags:
    - remove
    - unbound

#-------------------------------------------------------------------------------
# PACKAGING
#-------------------------------------------------------------------------------

- name: 'package remove unbound'
  package:
    state: 'absent'
    name: "{{package_name_unbound}}"
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - remove
    - unbound

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file remove unbound.cfg'
  file:
    state: 'absent'
    path: "{{file_dst_unbound_cfg}}"
  notify: 'service reload monit'
  tags:
    - remove
    - unbound

- name: 'line remove unbound_enable'
  lineinfile:
    state: 'absent'
    line: "{{file_line_unbound_enable}}=\"NO\" # Ansible: Remove unbound"
    regexp: "^{{file_line_unbound_enable}}="
    dest: "{{file_dst_unbound_enable}}"
    create: 'yes'
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - remove
    - unbound

- name: 'file remove unbound.conf.link'
  file:
    state: 'absent'
    path: "{{file_dst_unbound_conf_link}}"
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - remove
    - unbound

- name: 'file remove unbound.conf'
  file:
    state: 'absent'
    path: "{{file_dst_unbound_conf}}"
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - remove
    - unbound

- name: 'file remove root.hints.link'
  file:
    state: 'absent'
    path: "{{file_dst_root_hints_link}}"
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - remove
    - root

- name: 'file remove root.hints'
  file:
    state: 'absent'
    path: "{{file_dst_root_hints}}"
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - remove
    - unbound
