---

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - freebsd_periodic

- name: 'file remove periodic.conf'
  file:
    state: 'absent'
    path: "{{file_dst_periodic_conf}}"
  tags:
    - freebsd_periodic
