---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - rsyslog

- name: create file rsyslog.conf
  template:
    src: "{{file_src_rsyslog_conf}}"
    dest: "{{file_dst_rsyslog_conf}}"
    mode: "{{file_mode_rsyslog_conf}}"
    owner: "{{file_owner_rsyslog_conf}}"
    group: "{{file_group_rsyslog_conf}}"
  notify: restart service rsyslogd
  tags:
    - rsyslog

- name: create file rsyslog.cfg
  template:
    src: "{{file_src_rsyslog_cfg}}"
    dest: "{{file_dst_rsyslog_cfg}}"
    mode: "{{file_mode_rsyslog_cfg}}"
    owner: "{{file_owner_rsyslog_cfg}}"
    group: "{{file_group_rsyslog_cfg}}"
  notify: reload service monit
  when: (rsyslog_monitor_monit_state is match('true|yes|enable'))
  tags:
    - rsyslog

- name: status rsyslogd
  command: "{{command_cmd_status_rsyslogd}}"
  register: register_status_rsyslogd
  changed_when: (register_status_rsyslogd.rc > 1)
  failed_when: (register_status_rsyslogd.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - rsyslog

- name: enable rsyslogd
  command: "{{command_cmd_enable_rsyslogd}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_status_rsyslogd.rc == 1)
  tags:
    - rsyslog

- name: check rsyslogd
  command: "{{command_cmd_check_rsyslogd}}"
  register: register_check_rsyslogd
  changed_when: (register_check_rsyslogd.rc > 1)
  failed_when: (register_check_rsyslogd.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - rsyslog

- name: start rsyslogd
  command: "{{command_cmd_start_rsyslogd}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_check_rsyslogd.rc == 1)
  tags:
    - rsyslog

- name: start service rsyslogd
  service:
    state: 'started'
    enabled: 'yes'
    name: "{{service_name_rsyslogd}}"
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - rsyslog
