---

- name: import tasks install
  import_tasks: install.yml
  when: not (rsyslog_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - rsyslog

- name: import tasks config
  import_tasks: config.yml
  when: not (rsyslog_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - rsyslog

- name: import tasks enable
  import_tasks: enable.yml
  when: (rsyslog_state is match('start|on|enable'))
  tags:
    - rsyslog

- name: import tasks disable
  import_tasks: disable.yml
  when: (rsyslog_state is match('stop|off|disable'))
  tags:
    - rsyslog

- name: import tasks remove
  import_tasks: remove.yml
  when: (rsyslog_state is match('false|no|remove'))
  tags:
    - rsyslog
