---

- name: import tasks install
  import_tasks: install.yml
  when: not (colorls_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - colorls

- name: import tasks remove
  import_tasks: remove.yml
  when: (colorls_state is match('false|no|remove'))
  tags:
    - colorls
