---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - zfs

- name: create file zfs_check-pools
  template:
    src: "{{file_src_zfs_check_pools}}"
    dest: "{{file_dst_zfs_check_pools}}"
    mode: "{{file_mode_zfs_check_pools}}"
    owner: "{{file_owner_zfs_check_pools}}"
    group: "{{file_group_zfs_check_pools}}"
  tags:
    - zfs

- name: create file zfs_scrub-pools
  template:
    src: "{{file_src_zfs_scrub_pools}}"
    dest: "{{file_dst_zfs_scrub_pools}}"
    mode: "{{file_mode_zfs_scrub_pools}}"
    owner: "{{file_owner_zfs_scrub_pools}}"
    group: "{{file_group_zfs_scrub_pools}}"
  tags:
    - zfs

- name: create file zfs_trim-pools
  template:
    src: "{{file_src_zfs_trim_pools}}"
    dest: "{{file_dst_zfs_trim_pools}}"
    mode: "{{file_mode_zfs_trim_pools}}"
    owner: "{{file_owner_zfs_trim_pools}}"
    group: "{{file_group_zfs_trim_pools}}"
  tags:
    - zfs
