---

- name: import tasks install
  import_tasks: install.yml
  when: not (less_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - less

- name: import tasks remove
  import_tasks: remove.yml
  when: (less_state is match('false|no|remove'))
  tags:
    - less
