---

- name: 'task include install'
  import_tasks: install.yml
  when: not (bsd_diff_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - bsd_diff

- name: 'task include remove'
  import_tasks: remove.yml
  when: (bsd_diff_state is match('false|no|remove'))
  tags:
    - bsd_diff
