---

- name: import tasks install
  import_tasks: install.yml
  when: not (bsd_diff_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - bsd_diff

- name: import tasks remove
  import_tasks: remove.yml
  when: (bsd_diff_state is match('false|no|remove'))
  tags:
    - bsd_diff
