#!/bin/sh

{{ansible_managed|comment(decoration='#')}}

# This file sets up the tap device.
# It gives you the freedom to do anything you want with it.
# Use the correct name for the tap device:
# The environment variable $INTERFACE is set to the right name
# on most platforms, but if it doesn't work try to set it manually.

# Give it the right ip and netmask. Remember, the subnet of the
# tap device must be larger than that of the individual Subnets
# as defined in the host configuration file!
ifconfig $INTERFACE {{item.address}} netmask {{item.netmask}}
{% for route in (item.routes|default([])) %}
route add -net {{route.subnet}} {{route.gateway}}
{% endfor %}
