---

- name: import tasks install
  import_tasks: install.yml
  when: not (mailx_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - mailx

- name: import tasks remove
  import_tasks: remove.yml
  when: (mailx_state is match('false|no|remove'))
  tags:
    - mailx
