---

- name: import tasks install
  import_tasks: install.yml
  when: not (file_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - file

- name: import tasks remove
  import_tasks: remove.yml
  when: (file_state is match('false|no|remove'))
  tags:
    - file
