---

- name: import tasks install
  import_tasks: install.yml
  when: not (git_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - git

- name: import tasks remove
  import_tasks: remove.yml
  when: (git_state is match('false|no|remove'))
  tags:
    - git
