---

- name: import tasks install
  import_tasks: install.yml
  when: not (vlock_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - vlock

- name: import tasks remove
  import_tasks: remove.yml
  when: (vlock_state is match('false|no|remove'))
  tags:
    - vlock
