---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'

- name: validate monit
  command: "{{command_cmd_validate_monit}}"

- name: restart service monit
  service:
    state: 'restarted'
    name: "{{service_name_monit}}"
