---

- name: import tasks install
  import_tasks: install.yml
  when: not (sshpass_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - sshpass

- name: import tasks remove
  import_tasks: remove.yml
  when: (sshpass_state is match('false|no|remove'))
  tags:
    - sshpass
