---

- name: import tasks install
  import_tasks: install.yml
  when: not (ngrep_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - ngrep

- name: import tasks remove
  import_tasks: remove.yml
  when: (ngrep_state is match('false|no|remove'))
  tags:
    - ngrep
