---

- name: import tasks install
  import_tasks: install.yml
  when: not (zip_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - zip

- name: import tasks remove
  import_tasks: remove.yml
  when: (zip_state is match('false|no|remove'))
  tags:
    - zip
