---

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - freebsd_rc

- name: 'line config rc'
  lineinfile:
    state: "{{'absent' if ((item.state|default('true')) is match('false|no|remove')) else 'present'}}"
    line: "{{item.name}}=\"{{item.value}}\" # Ansible: {{(item.comment|default(''))}}"
    regexp: "^{{item.name}}="
    dest: "{{item.path if not ((item.path|default('')) == '') else file_dst_rc_conf}}"
    create: 'yes'
  loop: "{{freebsd_rc_config_all + freebsd_rc_config_group + freebsd_rc_config_host}}"
  tags:
    - freebsd_rc
