---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - lftp

- name: install package lftp
  package:
    state: 'present'
    name: "{{package_name_lftp}}"
  tags:
    - lftp
