---

- name: import tasks install
  import_tasks: install.yml
  when: not (lftp_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - lftp

- name: import tasks remove
  import_tasks: remove.yml
  when: (lftp_state is match('false|no|remove'))
  tags:
    - lftp
