---

- name: import tasks install
  import_tasks: install.yml
  when: not (netcat_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - netcat

- name: import tasks remove
  import_tasks: remove.yml
  when: (netcat_state is match('false|no|remove'))
  tags:
    - netcat
