---

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - netcat

- name: 'package remove netcat'
  package:
    state: 'absent'
    name: "{{package_name_netcat}}"
  tags:
    - netcat
