---

- name: import tasks install
  import_tasks: install.yml
  when: not (python_paramiko_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - python_paramiko

- name: import tasks remove
  import_tasks: remove.yml
  when: (python_paramiko_state is match('false|no|remove'))
  tags:
    - python_paramiko
