---

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - restic

- name: 'package remove restic'
  package:
    state: 'absent'
    name: "{{package_name_restic}}"
  tags:
    - restic

- name: 'cron remove restic_run-backup'
  cron:
    state: 'absent'
    name: "{{cron_name_restic_run_backup}}"
    user: "{{cron_user_restic_run_backup}}"
  tags:
    - restic

- name: 'file remove restic_run-backup'
  file:
    state: 'absent'
    path: "{{file_dst_restic_run_backup}}"
  no_log: 'true'
  tags:
    - restic

- name: 'file remove restic_etc.dir'
  file:
    state: 'absent'
    path: "{{file_dst_restic_etc_dir}}"
  tags:
    - restic
