---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - config
    - monit

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file create config'
  template:
    src: "{{file_src_config}}"
    dest: "{{file_dst_monit_d}}/{{item.name}}.cfg"
    mode: "{{file_mode_config}}"
    owner: "{{file_owner_config}}"
    group: "{{file_group_config}}"
  loop: "{{monit_config_all + monit_config_group + monit_config_host}}"
  notify:
    - 'command validate monit'
    - 'service restart monit'
  when: not (item.state is match('false|no|remove'))
  tags:
    - config
    - monit

- name: 'file remove config'
  file:
    state: 'absent'
    path: "{{file_dst_monit_d}}/{{item.name}}.cfg"
  loop: "{{monit_config_all + monit_config_group + monit_config_host}}"
  notify:
    - 'command validate monit'
    - 'service restart monit'
  when: (item.state is match('false|no|remove'))
  tags:
    - config
    - monit
