---

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - monit

- name: 'file create monitrc'
  template:
    src: "{{file_src_monitrc}}"
    dest: "{{file_dst_monitrc}}"
    mode: "{{file_mode_monitrc}}"
    owner: "{{file_owner_monitrc}}"
    group: "{{file_group_monitrc}}"
  tags:
    - monit

- name: 'line disable monit_enable'
  lineinfile:
    state: 'present'
    line: "{{file_line_monit_enable}}=\"NO\" # Ansible: Disable monit"
    regexp: "^{{file_line_monit_enable}}="
    dest: "{{file_dst_monit_enable}}"
    create: 'yes'
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - monit

- name: 'command status monit'
  command: "{{command_cmd_status_monit}}"
  register: register_status_monit
  changed_when: (register_status_monit.rc > 1)
  failed_when: (register_status_monit.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - monit

- name: 'command disable monit'
  command: "{{command_cmd_disable_monit}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_status_monit.rc == 0)
  tags:
    - monit

- name: 'command check monit'
  command: "{{command_cmd_check_monit}}"
  register: register_check_monit
  changed_when: (register_check_monit.rc > 1)
  failed_when: (register_check_monit.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - monit

- name: 'command stop monit'
  command: "{{command_cmd_stop_monit}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_check_monit.rc == 0)
  tags:
    - monit

- name: 'service stop monit'
  service:
    state: 'stopped'
    enabled: 'no'
    name: "{{service_name_monit}}"
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - monit
