---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - enable
    - monit

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file create monitrc'
  template:
    src: "{{file_src_monitrc}}"
    dest: "{{file_dst_monitrc}}"
    mode: "{{file_mode_monitrc}}"
    owner: "{{file_owner_monitrc}}"
    group: "{{file_group_monitrc}}"
  notify:
    - 'command validate monit'
    - 'service restart monit'
  tags:
    - enable
    - monit

- name: 'line enable monit_enable'
  lineinfile:
    state: 'present'
    line: "{{file_line_monit_enable}}=\"YES\" # Ansible: Enable monit"
    regexp: "^{{file_line_monit_enable}}="
    dest: "{{file_dst_monit_enable}}"
    create: 'yes'
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - enable
    - monit

#-------------------------------------------------------------------------------
# COMMANDS
#-------------------------------------------------------------------------------

- name: 'command status monit'
  command: "{{command_cmd_status_monit}}"
  register: register_status_monit
  changed_when: (register_status_monit.rc > 1)
  failed_when: (register_status_monit.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - enable
    - monit

- name: 'command enable monit'
  command: "{{command_cmd_enable_monit}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_status_monit.rc == 1)
  tags:
    - enable
    - monit

- name: 'command check monit'
  command: "{{command_cmd_check_monit}}"
  register: register_check_monit
  changed_when: (register_check_monit.rc > 1)
  failed_when: (register_check_monit.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - enable
    - monit

- name: 'command start monit'
  command: "{{command_cmd_start_monit}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_check_monit.rc == 1)
  tags:
    - enable
    - monit

#-------------------------------------------------------------------------------
# SYSTEM
#-------------------------------------------------------------------------------

- name: 'service start monit'
  service:
    state: 'started'
    enabled: 'yes'
    name: "{{service_name_monit}}"
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - enable
    - monit
