---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - enable
    - freebsd_pf

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file create anchors.conf'
  template:
    src: "{{file_src_anchors_conf}}"
    dest: "{{file_dst_anchors_conf}}"
    mode: "{{file_mode_anchors_conf}}"
    owner: "{{file_owner_anchors_conf}}"
    group: "{{file_group_anchors_conf}}"
  notify:
    - 'command validate freebsd_pf'
    - 'command reload freebsd_pf'
  tags:
    - enable
    - freebsd_pf

- name: 'file create filters.conf'
  template:
    src: "{{file_src_filters_conf}}"
    dest: "{{file_dst_filters_conf}}"
    mode: "{{file_mode_filters_conf}}"
    owner: "{{file_owner_filters_conf}}"
    group: "{{file_group_filters_conf}}"
  notify:
    - 'command validate freebsd_pf'
    - 'command reload freebsd_pf'
  tags:
    - enable
    - freebsd_pf

- name: 'file create macros.conf'
  template:
    src: "{{file_src_macros_conf}}"
    dest: "{{file_dst_macros_conf}}"
    mode: "{{file_mode_macros_conf}}"
    owner: "{{file_owner_macros_conf}}"
    group: "{{file_group_macros_conf}}"
  notify:
    - 'command validate freebsd_pf'
    - 'command reload freebsd_pf'
  tags:
    - enable
    - freebsd_pf

- name: 'file create normalization.conf'
  template:
    src: "{{file_src_normalization_conf}}"
    dest: "{{file_dst_normalization_conf}}"
    mode: "{{file_mode_normalization_conf}}"
    owner: "{{file_owner_normalization_conf}}"
    group: "{{file_group_normalization_conf}}"
  notify:
    - 'command validate freebsd_pf'
    - 'command reload freebsd_pf'
  tags:
    - enable
    - freebsd_pf

- name: 'file create options.conf'
  template:
    src: "{{file_src_options_conf}}"
    dest: "{{file_dst_options_conf}}"
    mode: "{{file_mode_options_conf}}"
    owner: "{{file_owner_options_conf}}"
    group: "{{file_group_options_conf}}"
  notify:
    - 'command validate freebsd_pf'
    - 'command reload freebsd_pf'
  tags:
    - enable
    - freebsd_pf

- name: 'file create queues.conf'
  template:
    src: "{{file_src_queues_conf}}"
    dest: "{{file_dst_queues_conf}}"
    mode: "{{file_mode_queues_conf}}"
    owner: "{{file_owner_queues_conf}}"
    group: "{{file_group_queues_conf}}"
  notify:
    - 'command validate freebsd_pf'
    - 'command reload freebsd_pf'
  tags:
    - enable
    - freebsd_pf

- name: 'file create tables.conf'
  template:
    src: "{{file_src_tables_conf}}"
    dest: "{{file_dst_tables_conf}}"
    mode: "{{file_mode_tables_conf}}"
    owner: "{{file_owner_tables_conf}}"
    group: "{{file_group_tables_conf}}"
  notify:
    - 'command validate freebsd_pf'
    - 'command reload freebsd_pf'
  tags:
    - enable
    - freebsd_pf

- name: 'file create translations.conf'
  template:
    src: "{{file_src_translations_conf}}"
    dest: "{{file_dst_translations_conf}}"
    mode: "{{file_mode_translations_conf}}"
    owner: "{{file_owner_translations_conf}}"
    group: "{{file_group_translations_conf}}"
  notify:
    - 'command validate freebsd_pf'
    - 'command reload freebsd_pf'
  tags:
    - enable
    - freebsd_pf

- name: 'file create pf.conf'
  template:
    src: "{{file_src_pf_conf}}"
    dest: "{{file_dst_pf_conf}}"
    mode: "{{file_mode_pf_conf}}"
    owner: "{{file_owner_pf_conf}}"
    group: "{{file_group_pf_conf}}"
  notify:
    - 'command validate freebsd_pf'
    - 'command reload freebsd_pf'
  tags:
    - enable
    - freebsd_pf

- name: 'line enable pf_enable'
  lineinfile:
    state: 'present'
    line: "{{file_line_pf_enable}}=\"YES\" # Ansible: Enable pf"
    regexp: "^{{file_line_pf_enable}}="
    dest: "{{file_dst_pf_enable}}"
    create: 'yes'
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - enable
    - freebsd_pf

- name: 'line enable gateway-ipv4'
  lineinfile:
    state: 'present'
    line: "{{file_line_gateway_ipv4}}=\"YES\" # Ansible: Enable gateway-ipv4"
    regexp: "^{{file_line_gateway_ipv4}}="
    dest: "{{file_dst_gateway_ipv4}}"
    create: 'yes'
  when: (ansible_os_family == 'FreeBSD') and (freebsd_pf_gateway_ipv4_state is match('true|yes|enable'))
  tags:
    - enable
    - freebsd_pf

- name: 'line disable gateway-ipv4'
  lineinfile:
    state: 'present'
    line: "{{file_line_gateway_ipv4}}=\"NO\" # Ansible: Disable gateway-ipv4"
    regexp: "^{{file_line_gateway_ipv4}}="
    dest: "{{file_dst_gateway_ipv4}}"
    create: 'yes'
  when: (ansible_os_family == 'FreeBSD') and not (freebsd_pf_gateway_ipv4_state is match('true|yes|enable'))
  tags:
    - enable
    - freebsd_pf

- name: 'line enable gateway-ipv6'
  lineinfile:
    state: 'present'
    line: "{{file_line_gateway_ipv6}}=\"YES\" # Ansible: Enable gateway-ipv6"
    regexp: "^{{file_line_gateway_ipv6}}="
    dest: "{{file_dst_gateway_ipv6}}"
    create: 'yes'
  when: (ansible_os_family == 'FreeBSD') and (freebsd_pf_gateway_ipv6_state is match('true|yes|enable'))
  tags:
    - enable
    - freebsd_pf

- name: 'line disable gateway-ipv6'
  lineinfile:
    state: 'present'
    line: "{{file_line_gateway_ipv6}}=\"NO\" # Ansible: Disable gateway-ipv6"
    regexp: "^{{file_line_gateway_ipv6}}="
    dest: "{{file_dst_gateway_ipv6}}"
    create: 'yes'
  when: (ansible_os_family == 'FreeBSD') and not (freebsd_pf_gateway_ipv6_state is match('true|yes|enable'))
  tags:
    - enable
    - freebsd_pf

#-------------------------------------------------------------------------------
# SYSTEM
#-------------------------------------------------------------------------------

- name: 'service start freebsd_pf'
  service:
    state: 'started'
    enabled: 'yes'
    name: "{{service_name_freebsd_pf}}"
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - enable
    - freebsd_pf
