---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - freebsd_pf

- name: remove file anchors.conf
  file:
    state: 'absent'
    path: "{{file_dst_anchors_conf}}"
  tags:
    - freebsd_pf

- name: remove file filters.conf
  file:
    state: 'absent'
    path: "{{file_dst_filters_conf}}"
  tags:
    - freebsd_pf

- name: remove file macros.conf
  file:
    state: 'absent'
    path: "{{file_dst_macros_conf}}"
  tags:
    - freebsd_pf

- name: remove file normalization.conf
  file:
    state: 'absent'
    path: "{{file_dst_normalization_conf}}"
  tags:
    - freebsd_pf

- name: remove file options.conf
  file:
    state: 'absent'
    path: "{{file_dst_options_conf}}"
  tags:
    - freebsd_pf

- name: remove file queues.conf
  file:
    state: 'absent'
    path: "{{file_dst_queues_conf}}"
  tags:
    - freebsd_pf

- name: remove file tables.conf
  file:
    state: 'absent'
    path: "{{file_dst_tables_conf}}"
  tags:
    - freebsd_pf

- name: remove file translations.conf
  file:
    state: 'absent'
    path: "{{file_dst_translations_conf}}"
  tags:
    - freebsd_pf

- name: remove file pf.conf
  file:
    state: 'absent'
    path: "{{file_dst_pf_conf}}"
  tags:
    - freebsd_pf

- name: remove file pf.dir
  file:
    state: 'absent'
    path: "{{file_dst_ntp_script_dir}}"
  tags:
    - freebsd_pf

- name: line remove pf_enable
  lineinfile:
    state: 'absent'
    line: "{{file_line_pf_enable}}=\"NO\" # Ansible: Remove pf"
    regexp: "^{{file_line_pf_enable}}="
    dest: "{{file_dst_pf_enable}}"
    create: 'yes'
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - freebsd_pf

- name: line remove gateway-ipv4
  lineinfile:
    state: 'absent'
    line: "{{file_line_gateway_ipv4}}=\"NO\" # Ansible: Remove gateway-ipv4"
    regexp: "^{{file_line_gateway_ipv4}}="
    dest: "{{file_dst_gateway_ipv4}}"
    create: 'yes'
  when: (ansible_os_family == 'FreeBSD') and (freebsd_pf_gateway_ipv4_state is match('true|yes|enable'))
  tags:
    - freebsd_pf

- name: line remove gateway-ipv6
  lineinfile:
    state: 'absent'
    line: "{{file_line_gateway_ipv6}}=\"NO\" # Ansible: Remove gateway-ipv6"
    regexp: "^{{file_line_gateway_ipv6}}="
    dest: "{{file_dst_gateway_ipv6}}"
    create: 'yes'
  when: (ansible_os_family == 'FreeBSD') and (freebsd_pf_gateway_ipv6_state is match('true|yes|enable'))
  tags:
    - freebsd_pf
