---

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_os_family}}{{ansible_distribution_release}}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - 'vars/main.yml'
  tags:
    - nsd

- name: 'file create nsd.conf'
  template:
    src: "{{file_src_nsd_conf}}"
    dest: "{{file_dst_nsd_conf}}"
    mode: "{{file_mode_nsd_conf}}"
    owner: "{{file_owner_nsd_conf}}"
    group: "{{file_group_nsd_conf}}"
    validate: "{{file_validate_nsd_conf}}"
  tags:
    - nsd

- name: 'line disable nsd_enable'
  lineinfile:
    state: 'present'
    line: "{{file_line_nsd_enable}}=\"NO\" # Ansible: Disable nsd"
    regexp: "^{{file_line_nsd_enable}}="
    dest: "{{file_dst_nsd_enable}}"
    create: 'yes'
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - nsd

- name: 'file create nsd.cfg'
  template:
    src: "{{file_src_nsd_cfg}}"
    dest: "{{file_dst_nsd_cfg}}"
    mode: "{{file_mode_nsd_cfg}}"
    owner: "{{file_owner_nsd_cfg}}"
    group: "{{file_group_nsd_cfg}}"
  notify: 'service reload monit'
  when: (nsd_monitor_monit_state is match('true|yes|enable'))
  tags:
    - nsd

- name: 'command status nsd'
  command: "{{command_cmd_status_nsd}}"
  register: register_status_nsd
  changed_when: (register_status_nsd.rc > 1)
  failed_when: (register_status_nsd.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - nsd

- name: 'command disable nsd'
  command: "{{command_cmd_disable_nsd}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_status_nsd.rc == 0)
  tags:
    - nsd

- name: 'command check nsd'
  command: "{{command_cmd_check_nsd}}"
  register: register_check_nsd
  changed_when: (register_check_nsd.rc > 1)
  failed_when: (register_check_nsd.rc > 1)
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD')
  tags:
    - nsd

- name: 'command stop nsd'
  command: "{{command_cmd_stop_nsd}}"
  check_mode: 'no'
  when: (ansible_os_family == 'OpenBSD') and (register_check_nsd.rc == 0)
  tags:
    - nsd

- name: 'service stop nsd'
  service:
    state: 'stopped'
    enabled: 'no'
    name: "{{service_name_nsd}}"
  when: (ansible_os_family == 'FreeBSD')
  tags:
    - nsd
