---

- name: import tasks install
  import_tasks: install.yml
  when: not (sysbench_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - sysbench

- name: import tasks remove
  import_tasks: remove.yml
  when: (sysbench_state is match('false|no|remove'))
  tags:
    - sysbench
