---

- name: import tasks install
  import_tasks: install.yml
  when: not (screen_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - screen

- name: import tasks remove
  import_tasks: remove.yml
  when: (screen_state is match('false|no|remove'))
  tags:
    - screen
